repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: debug-statements
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ".*/(inputs|example_inputs)/.*"
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: poetry run ruff format --diff
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        exclude: ".*/(inputs|example_inputs)/.*"
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
